"""add_user_onboarding_fields

Revision ID: e99c34b6bfdd
Revises: 242406320e71
Create Date: 2025-10-28 17:13:20.896214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e99c34b6bfdd'
down_revision: Union[str, None] = '242406320e71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: Removed checkpoint table drops - these are managed by LangGraph
    op.add_column('users', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('nationality', sa.String(), nullable=True))
    op.add_column('users', sa.Column('passport_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('country_of_residence', sa.String(), nullable=True))
    op.add_column('users', sa.Column('state_province', sa.String(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('emergency_contact_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('emergency_contact_phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('emergency_contact_relationship', sa.String(), nullable=True))
    op.add_column('users', sa.Column('has_pre_existing_conditions', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_frequent_traveler', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('preferred_coverage_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_onboarded', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarded_at')
    op.drop_column('users', 'is_onboarded')
    op.drop_column('users', 'preferred_coverage_type')
    op.drop_column('users', 'is_frequent_traveler')
    op.drop_column('users', 'has_pre_existing_conditions')
    op.drop_column('users', 'emergency_contact_relationship')
    op.drop_column('users', 'emergency_contact_phone')
    op.drop_column('users', 'emergency_contact_name')
    op.drop_column('users', 'postal_code')
    op.drop_column('users', 'city')
    op.drop_column('users', 'state_province')
    op.drop_column('users', 'country_of_residence')
    op.drop_column('users', 'passport_number')
    op.drop_column('users', 'nationality')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'date_of_birth')
    # NOTE: Removed checkpoint table creation - these are managed by LangGraph
    # ### end Alembic commands ###
